<Project Sdk="Microsoft.NET.Sdk">
    <ItemGroup>
      <ProjectReference Include="..\Start_Template_CSharp.Core\Start_Template_CSharp.Core.csproj" />
    </ItemGroup>
    <ItemGroup>
      <PackageReference Remove="Microsoft.Extensions.DependencyInjection" />
      <PackageReference Remove="Microsoft.Extensions.DependencyInjection.Abstractions" />
    </ItemGroup>
</Project>
