import StoreProvider from '@/lib/StoreProvider'
import type { Metadata } from 'next'
import '@/styles/main.scss'
import { Suspense } from 'react'
import Loading from './loading'
export const metadata: Metadata = {
	title: 'Add Employee App',
	description: 'Generated by create next app',
	keywords: [],
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang='en'>
			<body>
				<div className='container'>
					<StoreProvider>
						<Suspense fallback={<Loading />}>{children}</Suspense>
					</StoreProvider>
				</div>
			</body>
		</html>
	)
}
